### ISSUE TITLE
Multi-thread Calculation

### ISSUE THREAD

**Issue by SiyiWanggou** [cran/ccRemover#1]
Hi ccRemover Team,
     Is there any multi-thread calculation method for ccRemover?
     For large single cell RNAseq dataset, one core thread is too slow.

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Thanks!

**Comment by Laura19993** [comment]
Hi @SiyiWanggou 
I experience the same issue, ccRemover is way to slow for a big dataset. 
Did you find a solution?
Best,
Laura
